### ISSUE TITLE
Vault 1.5.0 - net.milkbowl.vault.chat.Chat.class returns null.

### ISSUE THREAD

**Issue by Chozo4** [MilkBowl/Vault#585]
The issue does not exist in the v1.4.1 [and earlier builds] thus have had continue using it for the time being as a result. I've been using the chat provider via Buscript to access PermissionsEx data such as the player prefix/tags as needed as part of a custom chat script. I have been accessing it via the following (.class is omitted due to already being treated as such):

PEX=server.getServicesManager().getRegistration(net.milkbowl.vault.chat.Chat).getProvider();

This has worked fine until 1.5.0 which when attempting to access will state the following via console:
[04:49:16 WARN]: [Buscript] Error running script: TypeError: Cannot call method "getProvider" of null (plugins\Buscript\startup-script.txt#30).

It is being run on the latest 1.8.1 Spigot Buildtools build.

**Comment by Chozo4** [comment]
It seems the update was build on MD_5's EcoCityCraft Jenkins (http://ci.ecocitycraft.com/job/Vault/9/) as version 1.5.1. I have tested that build with similar results.

[22:40:46] [Server thread/WARN]: [Buscript] Task #23 for Buscript v1.1-b28 generated an exception
java.lang.NoClassDefFoundError: com/earth2me/essentials/OfflinePlayer
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_25]
	at java.lang.Class.privateGetDeclaredMethods(Unknown Source) ~[?:1.8.0_25]
	at java.lang.Class.privateGetPublicMethods(Unknown Source) ~[?:1.8.0_25]
	at java.lang.Class.getMethods(Unknown Source) ~[?:1.8.0_25]
	at org.mozilla.javascript.JavaMembers.discoverAccessibleMethods(JavaMembers.java:346) ~[?:?]
	at org.mozilla.javascript.JavaMembers.discoverAccessibleMethods(JavaMembers.java:302) ~[?:?]
	at org.mozilla.javascript.JavaMembers.reflect(JavaMembers.java:419) ~[?:?]
	at org.mozilla.javascript.JavaMembers.<init>(JavaMembers.java:43) ~[?:?]
	at org.mozilla.javascript.JavaMembers.lookupClass(JavaMembers.java:807) ~[?:?]
	at org.mozilla.javascript.NativeJavaObject.initMembers(NativeJavaObject.java:54) ~[?:?]
	at org.mozilla.javascript.NativeJavaObject.<init>(NativeJavaObject.java:44) ~[?:?]
	at org.mozilla.javascript.NativeJavaObject.<init>(NativeJavaObject.java:34) ~[?:?]
	at org.mozilla.javascript.WrapFactory.wrapAsJavaObject(WrapFactory.java:115) ~[?:?]
	at org.mozilla.javascript.WrapFactory.wrap(WrapFactory.java:72) ~[?:?]
	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:236) ~[?:?]
	at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java:85) ~[?:?]
	at org.mozilla.javascript.gen.plugins_Buscript_startup_script_txt_1._c_script_0(plugins\Buscript\startup-script.txt:30) ~[?:?]
	at org.mozilla.javascript.gen.plugins_Buscript_startup_script_txt_1.call(plugins\Buscript\startup-script.txt) ~[?:?]
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394) ~[?:?]
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3091) ~[?:?]
	at org.mozilla.javascript.gen.plugins_Buscript_startup_script_txt_1.call(plugins\Buscript\startup-script.txt) ~[?:?]
	at org.mozilla.javascript.gen.plugins_Buscript_startup_script_txt_1.exec(plugins\Buscript\startup-script.txt) ~[?:?]
	at org.mozilla.javascript.Context.evaluateReader(Context.java:1110) ~[?:?]
	at buscript.Buscript.runScript(Buscript.java:677) ~[?:?]
	at buscript.Buscript.executeScript(Buscript.java:539) ~[?:?]
	at buscript.Buscript.executeScript(Buscript.java:505) ~[?:?]
	at buscript.BuscriptPlugin$1.run(BuscriptPlugin.java:27) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8-R0.1-b35.jar:git-Spigot-13716d9-bd703b8]
	at org.bukkit.craftbukkit.v1_8_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8-R0.1-b35.jar:git-Spigot-13716d9-bd703b8]
	at net.minecraft.server.v1_8_R1.MinecraftServer.z(MinecraftServer.java:694) [spigot-1.8-R0.1-b35.jar:git-Spigot-13716d9-bd703b8]
	at net.minecraft.server.v1_8_R1.DedicatedServer.z(DedicatedServer.java:316) [spigot-1.8-R0.1-b35.jar:git-Spigot-13716d9-bd703b8]
	at net.minecraft.server.v1_8_R1.MinecraftServer.y(MinecraftServer.java:623) [spigot-1.8-R0.1-b35.jar:git-Spigot-13716d9-bd703b8]
	at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:526) [spigot-1.8-R0.1-b35.jar:git-Spigot-13716d9-bd703b8]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_25]
Caused by: java.lang.ClassNotFoundException: com.earth2me.essentials.OfflinePlayer
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_25]
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_25]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_25]
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_25]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.8-R0.1-b35.jar:git-Spigot-13716d9-bd703b8]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.8-R0.1-b35.jar:git-Spigot-13716d9-bd703b8]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_25]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_25]
	... 34 more

**Comment by Sleaker** [comment]
can't duplicate this and can't find it as an issue. neither repository is current. Make sure you're using official builds. PEX 1.22 specifically.
