### ISSUE TITLE
Vault generated ane xception while executing task 3

### ISSUE THREAD

**Issue by xtomyserrax** [MilkBowl/Vault#587]
What this warn means? Its annoying to read this in console if its not a bug/problem

[21:43:18] [pool-3-thread-1/WARN]: Exception in thread "pool-3-thread-1" 
[21:43:18] [pool-3-thread-1/WARN]: org.apache.commons.lang.UnhandledException: Plugin Vault v1.5.0-b28 generated an exception while executing task 3
	at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()Ljava/util/Collection;
	at net.milkbowl.vault.Metrics.postPlugin(Metrics.java:387)
	at net.milkbowl.vault.Metrics.access$400(Metrics.java:63)
	at net.milkbowl.vault.Metrics$4.run(Metrics.java:275)
	at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftTask.run(CraftTask.java:53)
	at org.bukkit.craftbukkit.v1_7_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
	... 3 more

**Comment by Chozo4** [comment]
This is a duplicate issue of #586 . 1.5+ will not with with any versions lower than 1.8 as clearly stated.
