### ISSUE TITLE
Error Codes in console

### ISSUE THREAD

**Issue by XLG-DrTankHead** [MilkBowl/Vault#594]
08:09:51 [SEVERE] Exception in thread "pool-1-thread-1"
08:09:51 [SEVERE] org.apache.commons.lang.UnhandledException: Plugin Vault v1.5.
2-b33 generated an exception while executing task 17
        at org.bukkit.craftbukkit.v1_6_R3.scheduler.CraftAsyncTask.run(CraftAsyn
cTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()Ljav
a/util/Collection;
        at net.milkbowl.vault.Metrics.postPlugin(Metrics.java:387)
        at net.milkbowl.vault.Metrics.access$400(Metrics.java:63)
        at net.milkbowl.vault.Metrics$4.run(Metrics.java:275)
        at org.bukkit.craftbukkit.v1_6_R3.scheduler.CraftTask.run(CraftTask.java
:53)
        at org.bukkit.craftbukkit.v1_6_R3.scheduler.CraftAsyncTask.run(CraftAsyn
cTask.java:53)
        ... 3 more

**Comment by XLG-DrTankHead** [comment]
All of my other plugins are running fine, vault is causing these errors alone

**Comment by Sleaker** [comment]
Vault 1.5 explicitly states it is for bukkit servers built on MC 1.8. Please make sure you're using a compatible Vault version for the server version you're using.
