### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by SubmissiveMC** [MilkBowl/Vault#626]
Hey I've been having issues with my rank prefixes and even though this may be unrelated, I was getting this vault error on startup. Would you mind explaining whats up? Thanks :)

[23:06:00] [Server thread/ERROR]: Could not load 'plugins/Vault.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.IllegalArgumentException: Plugin already initialized!
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[server.jar:git-Spigot-044d928-e8c6403]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[server.jar:git-Spigot-044d928-e8c6403]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [server.jar:git-Spigot-044d928-e8c6403]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:291) [server.jar:git-Spigot-044d928-e8c6403]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198) [server.jar:git-Spigot-044d928-e8c6403]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:528) [server.jar:git-Spigot-044d928-e8c6403]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_31]
Caused by: java.lang.IllegalArgumentException: Plugin already initialized!
	at org.bukkit.plugin.java.PluginClassLoader.initialize(PluginClassLoader.java:122) ~[server.jar:git-Spigot-044d928-e8c6403]
	at org.bukkit.plugin.java.JavaPlugin.<init>(JavaPlugin.java:66) ~[server.jar:git-Spigot-044d928-e8c6403]
	at net.milkbowl.vault.Vault.<init>(Vault.java:107) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_31]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_31]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_31]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408) ~[?:1.8.0_31]
	at java.lang.Class.newInstance(Class.java:438) ~[?:1.8.0_31]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76) ~[server.jar:git-Spigot-044d928-e8c6403]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[server.jar:git-Spigot-044d928-e8c6403]
	... 6 more
Caused by: java.lang.IllegalStateException: Initial initialization
	at org.bukkit.plugin.java.PluginClassLoader.initialize(PluginClassLoader.java:125) ~[server.jar:git-Spigot-044d928-e8c6403]
	at org.bukkit.plugin.java.JavaPlugin.<init>(JavaPlugin.java:66) ~[server.jar:git-Spigot-044d928-e8c6403]
	at com.onarandombox.MultiversePortals.MultiversePortals.<init>(MultiversePortals.java:60) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_31]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_31]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_31]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408) ~[?:1.8.0_31]
	at java.lang.Class.newInstance(Class.java:438) ~[?:1.8.0_31]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76) ~[server.jar:git-Spigot-044d928-e8c6403]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[server.jar:git-Spigot-044d928-e8c6403]
	... 6 more

**Comment by Noket** [comment]
Object construction should only be happening at startup (via java.reflect),
and only once. The error message means, basically, that the plugin is
already loaded.

Are you using /reload to test your prefixes? You should be stopping and
starting the server to test plugin changes.

**Comment by Sleaker** [comment]
This issue is generally related to Multiverse and it's subsystems, please verify that you're not using Multiverse-Portals or that you have updated t oa version where the author has fixed the issue.

**Comment by SubmissiveMC** [comment]
So I disabled Multiverse portals and the console error goes away and stuff, but I need Multiverse Portals for the server, is there any way to get both of them running side by side?

**Comment by Sleaker** [comment]
You need to see if there is a fixed version available. Unfortunately because this issue is in Multiverse I can't help you.

**Comment by PinoyLifeCraft** [comment]
:disappointed: no Multiverse Portal it's bad! :-1:
