### ISSUE TITLE
Error in [ 1.8.3 ] ??

### ISSUE THREAD

**Issue by PinoyLifeCraft** [MilkBowl/Vault#631]
[21:23:57] [Server thread/ERROR]: Could not load 'plugins\Vault.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.IllegalArgumentException: Plugin already initialized!
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[craftbukkit.jar:git-Bukkit-0a645a2]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:328) ~[craftbukkit.jar:git-Bukkit-0a645a2]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [craftbukkit.jar:git-Bukkit-0a645a2]
	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.loadPlugins(CraftServer.java:288) [craftbukkit.jar:git-Bukkit-0a645a2]
	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.<init>(CraftServer.java:250) [craftbukkit.jar:git-Bukkit-0a645a2]
	at net.minecraft.server.v1_8_R2.PlayerList.<init>(PlayerList.java:69) [craftbukkit.jar:git-Bukkit-0a645a2]
	at net.minecraft.server.v1_8_R2.DedicatedPlayerList.<init>(SourceFile:14) [craftbukkit.jar:git-Bukkit-0a645a2]
	at net.minecraft.server.v1_8_R2.DedicatedServer.init(DedicatedServer.java:180) [craftbukkit.jar:git-Bukkit-0a645a2]
	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:501) [craftbukkit.jar:git-Bukkit-0a645a2]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_60]
Caused by: java.lang.IllegalArgumentException: Plugin already initialized!
	at org.bukkit.plugin.java.PluginClassLoader.initialize(PluginClassLoader.java:98) ~[craftbukkit.jar:git-Bukkit-0a645a2]
	at org.bukkit.plugin.java.JavaPlugin.<init>(JavaPlugin.java:66) ~[craftbukkit.jar:git-Bukkit-0a645a2]
	at net.milkbowl.vault.Vault.<init>(Vault.java:107) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_60]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_60]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_60]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_60]
	at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_60]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:52) ~[craftbukkit.jar:git-Bukkit-0a645a2]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[craftbukkit.jar:git-Bukkit-0a645a2]
	... 9 more
Caused by: java.lang.IllegalStateException: Initial initialization
	at org.bukkit.plugin.java.PluginClassLoader.initialize(PluginClassLoader.java:101) ~[craftbukkit.jar:git-Bukkit-0a645a2]
	at org.bukkit.plugin.java.JavaPlugin.<init>(JavaPlugin.java:66) ~[craftbukkit.jar:git-Bukkit-0a645a2]
	at com.onarandombox.MultiversePortals.MultiversePortals.<init>(MultiversePortals.java:60) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_60]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_60]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_60]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_60]
	at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_60]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:52) ~[craftbukkit.jar:git-Bukkit-0a645a2]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[craftbukkit.jar:git-Bukkit-0a645a2]
	... 9 more
[21:23:57] [Server thread/ERROR]: Could not load 'plugins\BuyCommand.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: Vault
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:219) [craftbukkit.jar:git-Bukkit-0a645a2]
	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.loadPlugins(CraftServer.java:288) [craftbukkit.jar:git-Bukkit-0a645a2]
	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.<init>(CraftServer.java:250) [craftbukkit.jar:git-Bukkit-0a645a2]
	at net.minecraft.server.v1_8_R2.PlayerList.<init>(PlayerList.java:69) [craftbukkit.jar:git-Bukkit-0a645a2]
	at net.minecraft.server.v1_8_R2.DedicatedPlayerList.<init>(SourceFile:14) [craftbukkit.jar:git-Bukkit-0a645a2]
	at net.minecraft.server.v1_8_R2.DedicatedServer.init(DedicatedServer.java:180) [craftbukkit.jar:git-Bukkit-0a645a2]
	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:501) [craftbukkit.jar:git-Bukkit-0a645a2]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_60]
[21:23:57] [Server thread/ERROR]: Could not load 'plugins\dtlTraders.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: Vault
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:219) [craftbukkit.jar:git-Bukkit-0a645a2]
	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.loadPlugins(CraftServer.java:288) [craftbukkit.jar:git-Bukkit-0a645a2]
	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.<init>(CraftServer.java:250) [craftbukkit.jar:git-Bukkit-0a645a2]
	at net.minecraft.server.v1_8_R2.PlayerList.<init>(PlayerList.java:69) [craftbukkit.jar:git-Bukkit-0a645a2]
	at net.minecraft.server.v1_8_R2.DedicatedPlayerList.<init>(SourceFile:14) [craftbukkit.jar:git-Bukkit-0a645a2]
	at net.minecraft.server.v1_8_R2.DedicatedServer.init(DedicatedServer.java:180) [craftbukkit.jar:git-Bukkit-0a645a2]
	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:501) [craftbukkit.jar:git-Bukkit-0a645a2]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_60]
[21:23:58] [Server thread/INFO]: [WorldEdit] Loading WorldEdit v6.1;no_git_id

**Comment by Sleaker** [comment]
Duplicate: see #626
