### ISSUE TITLE
Vault error

### ISSUE THREAD

**Issue by DuckCraftPvP** [MilkBowl/Vault#669]
Spigot version: 1.9.4
Vault Version: Latest
Reason error comes up: Idk, It spams console. 

[16:35:07 WARN]: org.apache.commons.lang.UnhandledException: Plugin Vault v1.4.1-b436 generated an exception while executing task 12
        at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
        at net.milkbowl.vault.Metrics.postPlugin(Metrics.java:387)
        at net.milkbowl.vault.Metrics.access$400(Metrics.java:63)
        at net.milkbowl.vault.Metrics$4.run(Metrics.java:275)
        at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_9_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more

**Comment by electronicboy** [comment]
Update the plugin, That version of Vault is old.

**Comment by DuckCraftPvP** [comment]
There is no new version qq.

**Comment by electronicboy** [comment]
http://dev.bukkit.org/bukkit-plugins/vault/

You're running 1.4.1. There is a much newer version on the dev bukkit page.
