### ISSUE TITLE
Vault not loading

### ISSUE THREAD

**Issue by xiaoqi7** [MilkBowl/Vault#679]
Hello, I am getting this error when I start Vault:
[19:14:36] [Server thread/ERROR]: Could not load 'plugins/Vault(2).jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:160) ~[server.jar:git-Spigot-f950f8e-622630c]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:133) [server.jar:git-Spigot-f950f8e-622630c]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.loadPlugins(CraftServer.java:300) [server.jar:git-Spigot-f950f8e-622630c]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:204) [server.jar:git-Spigot-f950f8e-622630c]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:542) [server.jar:git-Spigot-f950f8e-622630c]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72-internal]
Caused by: java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_72-internal]
	at java.util.zip.ZipFile.<init>(ZipFile.java:219) ~[?:1.8.0_72-internal]
	at java.util.zip.ZipFile.<init>(ZipFile.java:149) ~[?:1.8.0_72-internal]
	at java.util.jar.JarFile.<init>(JarFile.java:166) ~[?:1.8.0_72-internal]
	at java.util.jar.JarFile.<init>(JarFile.java:130) ~[?:1.8.0_72-internal]
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:148) ~[server.jar:git-Spigot-f950f8e-622630c]
	... 5 more

**Comment by Sleaker** [comment]
It looks like you may have downloaded vault multiple times or it may not have completed properly. try again.
