### ISSUE TITLE
Economy_Gringotts throwing field errors.

### ISSUE THREAD

**Issue by stuntguy3000** [MilkBowl/Vault#690]
```
19.06 01:44:13 [Server] INFO at java.lang.NoSuchFieldError: accountHolderFactory
19.06 01:44:13 [Server] INFO at net.milkbowl.vault.economy.plugins.Economy_Gringotts.getBalance(Economy_Gringotts.java:135) ~[?:?]
19.06 01:44:13 [Server] INFO at net.milkbowl.vault.economy.AbstractEconomy.getBalance(AbstractEconomy.java:20) ~[?:?]
19.06 01:44:13 [Server] INFO at de.codecrafter47.data.bukkit.vault.VaultBalanceProvider.lambda$apply0$0(VaultBalanceProvider.java:43) ~[?:?]
19.06 01:44:13 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftFuture.run(CraftFuture.java:89) ~[spigot-1.11.jar:git-Spigot-d5dfb24-ed8c725]
19.06 01:44:13 [Server] INFO at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.11.jar:git-Spigot-d5dfb24-ed8c725]
19.06 01:44:13 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:738) [spigot-1.11.jar:git-Spigot-d5dfb24-ed8c725]
19.06 01:44:13 [Server] INFO at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot-1.11.jar:git-Spigot-d5dfb24-ed8c725]
19.06 01:44:13 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.11.jar:git-Spigot-d5dfb24-ed8c725]
19.06 01:44:13 [Server] INFO at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.11.jar:git-Spigot-d5dfb24-ed8c725]
19.06 01:44:13 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
```

**Comment by Sleaker** [comment]
I can only think that maybe Gringotts isn't setup right if there's no accountHolderFactory, or you're using an incompatible version? Did they update and change some stuff recently?

**Comment by LemADEC** [comment]
This issue is still live with latest versions of Gringotts and Vault, please check it up
