### ISSUE TITLE
My Plugin does Not Work

### ISSUE THREAD

**Issue by mnjg123** [MilkBowl/Vault#698]
I Wroted an Plugin with Vault.

But it does not Load here´s the Console Error:

>  Could not load 'plugins\ReloadCMD.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.Error: Unresolved compilation problems:
        The import net.milkbowl cannot be resolved
        Economy cannot be resolved to a type
        Economy cannot be resolved to a type
        Economy cannot be resolved to a type
        The method getRegistration(Class<Economy>) from the type ServicesManager refers to the missing type Economy
        Economy cannot be resolved to a type
        Economy cannot be resolved to a type
        Economy cannot be resolved to a type
        Economy cannot be resolved to a type
        Economy cannot be resolved to a type

        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:292) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.reload(CraftServer.java:739) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.Bukkit.reload(Bukkit.java:535) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:25) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:627) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:412) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:375) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-21fe707-e1ebe52]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.lang.Error: Unresolved compilation problems:
        The import net.milkbowl cannot be resolved
        Economy cannot be resolved to a type
        Economy cannot be resolved to a type
        Economy cannot be resolved to a type
        The method getRegistration(Class<Economy>) from the type ServicesManager refers to the missing type Economy
        Economy cannot be resolved to a type
        Economy cannot be resolved to a type
        Economy cannot be resolved to a type
        Economy cannot be resolved to a type
        Economy cannot be resolved to a type

        at me.mnjg123.coins.main.Main.<init>(Main.java:11) ~[?:?]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_131]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_131]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_131]
        at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_131]
        at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_131]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[spigot.jar:git-Spigot-21fe707-e1ebe52]
        ... 14 more

>

**Comment by Sleaker** [comment]
make sure Vault is installed on the server.

**Comment by mnjg123** [comment]
It is installed!

**Comment by Sleaker** [comment]
You also have another 'The import net.milkbowl cannot be resolved' issue in here, is it that you can't even compile your plugin with Vault support? if that's the case, make sure you have your workspace setup when doing compilation so that vault is on the classpath.
