### ISSUE TITLE
Vault Conversion

### ISSUE THREAD

**Issue by ShaneBeee** [MilkBowl/Vault#725]
Hello

I currently am writing an Economy Skript. I had a developer create a Vault hook for skript, and every thing works totally awesome, except when I try to do a conversion from essentials to my economy. 
I have also messaged him, in the event something is missing in his add-on/plugin
This is the error it spews out when I try do the conversion

```
[15:36:55 WARN]: Unexpected exception while parsing console command "vault-convert EssentialsEconomy SkEco"
org.bukkit.command.CommandException: Unhandled exception executing command 'vault-convert' in plugin Vault v1.6.6-b${env.TRAVIS_BUILD_NUMBER}
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:634) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
	at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:444) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:407) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
Caused by: java.lang.UnsupportedOperationException: HasAccountRequest
	at us._donut_.skvault.CustomEconomy.hasAccount(CustomEconomy.java:295) ~[?:?]
	at net.milkbowl.vault.Vault.convertCommand(Vault.java:461) ~[?:?]
	at net.milkbowl.vault.Vault.onCommand(Vault.java:412) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.12.2.jar:git-Spigot-2086bb0-2f3ed3b]
	... 8 more
```

**Comment by DoNotSpamPls** [comment]
>skript

**Comment by ShaneBeee** [comment]
Never mind.  This was an issue with the addon for skript and it has been fixed.

**Comment by Sleaker** [comment]
Glad you figured out the issue!
