### ISSUE TITLE
Task Error

### ISSUE THREAD

**Issue by madtomic** [MilkBowl/Vault#735]
[07:22:48 WARN]: [Vault] Task #7 for Vault v1.5.6-b49 generated an exception
java.util.ConcurrentModificationException: null
        at java.util.HashMap$HashIterator.nextNode(Unknown Source) ~[?:1.8.0_172]
        at java.util.HashMap$KeyIterator.next(Unknown Source) ~[?:1.8.0_172]
        at org.bukkit.permissions.PermissibleBase.clearPermissions(PermissibleBase.java:168) ~[patched_1.12.2.jar:git-Paper-1470]
        at org.bukkit.permissions.PermissibleBase.recalculatePermissions(PermissibleBase.java:149) ~[patched_1.12.2.jar:git-Paper-1470]
        at me.lucko.luckperms.bukkit.model.permissible.MonitoredPermissibleBase.recalculatePermissions(MonitoredPermissibleBase.java:132) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.command.ServerCommandSender.recalculatePermissions(ServerCommandSender.java:66) ~[patched_1.12.2.jar:git-Paper-1470]
        at org.bukkit.plugin.SimplePluginManager.dirtyPermissibles(SimplePluginManager.java:689) ~[patched_1.12.2.jar:git-Paper-1470]
        at org.bukkit.plugin.SimplePluginManager.calculatePermissionDefault(SimplePluginManager.java:668) ~[patched_1.12.2.jar:git-Paper-1470]
        at org.bukkit.plugin.SimplePluginManager.addPermission(SimplePluginManager.java:640) ~[patched_1.12.2.jar:git-Paper-1470]
        at org.bukkit.plugin.SimplePluginManager.addPermission(SimplePluginManager.java:628) ~[patched_1.12.2.jar:git-Paper-1470]
        at net.milkbowl.vault.Vault$1.run(Vault.java:155) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63) ~[patched_1.12.2.jar:git-Paper-1470]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) [patched_1.12.2.jar:git-Paper-1470]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:833) [patched_1.12.2.jar:git-Paper-1470]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) [patched_1.12.2.jar:git-Paper-1470]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1470]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1470]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_172]
		
		
Startup error

**Comment by Sleaker** [comment]
See issue #719
