### ISSUE TITLE
Task #74 for Vault v1.7.1-b91 generated an exception java.lang.NoClassDefFoundError: 

### ISSUE THREAD

**Issue by marvinej** [MilkBowl/Vault#744]
[12:18:54 INFO]: This server is running CraftBukkit version git-Spigot-f823ac5-020b495 (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)

[12:12:09 WARN]: [Vault] Task #74 for Vault v1.7.1-b91 generated an exception
java.lang.NoClassDefFoundError: me/zombie_striker/pluginconstructor/privatemetrics/Metrics$CustomChart
        at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_181]
        at java.lang.Class.privateGetDeclaredMethods(Unknown Source) ~[?:1.8.0_181]
        at java.lang.Class.privateGetMethodRecursive(Unknown Source) ~[?:1.8.0_181]
        at java.lang.Class.getMethod0(Unknown Source) ~[?:1.8.0_181]
        at java.lang.Class.getMethod(Unknown Source) ~[?:1.8.0_181]
        at net.milkbowl.vault.metrics.bukkit.Metrics.submitData(Metrics.java:257) ~[?:?]
        at net.milkbowl.vault.metrics.bukkit.Metrics.access$100(Metrics.java:36) ~[?:?]
        at net.milkbowl.vault.metrics.bukkit.Metrics$1$1.run(Metrics.java:159) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot.jar:git-Spigot-f823ac5-020b495]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:361) [spigot.jar:git-Spigot-f823ac5-020b495]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:893) [spigot.jar:git-Spigot-f823ac5-020b495]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot.jar:git-Spigot-f823ac5-020b495]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:835) [spigot.jar:git-Spigot-f823ac5-020b495]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:733) [spigot.jar:git-Spigot-f823ac5-020b495]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: java.lang.ClassNotFoundException: me.zombie_striker.pluginconstructor.privatemetrics.Metrics$CustomChart
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_181]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:154) ~[spigot.jar:git-Spigot-f823ac5-020b495]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[spigot.jar:git-Spigot-f823ac5-020b495]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
        ... 15 more

**Comment by Sleaker** [comment]
On another read-through this report is very confusing, what is zombie_striker.privatemetrics.Metrics - did you try to override the original metrics provider or something?

**Comment by Sleaker** [comment]
Alright, looked through github, not a Vault issue, go bark up the chain zombie_strikers problem with PluginConstructor, not mine. Don't hotload classes.
