### ISSUE TITLE
plugin stopped working

### ISSUE THREAD

**Issue by ThePhoenix96** [MilkBowl/Vault#760]
hi, plugin stopped working idk why

Version: `git-Spigot-e6eb36f-d3ed151 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)[m`

Error: `Could not load 'plugins\Vault.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.IllegalArgumentException: Plugin already initialized!
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:139) ~[spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:332) ~[spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:252) [spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.loadPlugins(CraftServer.java:325) [spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:213) [spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:698) [spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: java.lang.IllegalArgumentException: Plugin already initialized!
	at org.bukkit.plugin.java.PluginClassLoader.initialize(PluginClassLoader.java:168) ~[spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]
	at org.bukkit.plugin.java.JavaPlugin.<init>(JavaPlugin.java:54) ~[spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]
	at net.milkbowl.vault.Vault.<init>(Vault.java:106) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_201]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_201]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_201]
	at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_201]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:72) ~[spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]
	... 6 more
Caused by: java.lang.IllegalStateException: Initial initialization
	at org.bukkit.plugin.java.PluginClassLoader.initialize(PluginClassLoader.java:171) ~[spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]
	at org.bukkit.plugin.java.JavaPlugin.<init>(JavaPlugin.java:54) ~[spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]
	at fr.rafoudiablol.ft.main.FairTrade.<init>(FairTrade.java:38) ~[?:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_201]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_201]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_201]
	at java.lang.Class.newInstance(Unknown Source) ~[?:1.8.0_201]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:72) ~[spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:332) ~[spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:277) ~[spigot-1.13.2.jar:git-Spigot-e6eb36f-d3ed151]
	... 4 more`

**Comment by Sleaker** [comment]
It's already loaded on your server. make sure you don't have it installed twice, or complain to FairTrade that it's doing something incorrect during it's own plugin loading.

**Comment by ThePhoenix96** [comment]
yep u was right that fair trade caused problems ty
