### ISSUE TITLE
Issues with Vault not hooking correctly

### ISSUE THREAD

**Issue by victoret7** [MilkBowl/Vault#803]
I'm been developing my plugin lately and i have hit a strange bug. After adding an update to ACF and some new APIs i began to have issues with worldguard, worldedit (That i solved editing the API since they don't support outdated versions) and after solving them i have gotten this one with vault that forces me to go to the drawing table. I do not know why I'm getting this issue and why the hell do Vault check permissions on bpermissions when im using Luckperms. Any help?

`[16:05:16] [Server thread/ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'dchat' in plugin DeluxeChat v1.13.1
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[server.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) ~[server.jar:git-PaperSpigot-"4c7641d"]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666) ~[server.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1189) [?:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1001) [?:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [server.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [server.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-PaperSpigot-"4c7641d"]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_242]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_242]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [server.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [server.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [server.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [server.jar:git-PaperSpigot-"4c7641d"]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [server.jar:git-PaperSpigot-"4c7641d"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.NoClassDefFoundError: de/bananaco/bpermissions/api/CalculableType
	at net.milkbowl.vault.chat.plugins.Chat_bPermissions2.getPlayerPrefix(Chat_bPermissions2.java:98) ~[Vault.jar:?]
	at net.milkbowl.vault.chat.Chat.getPlayerPrefix(Chat.java:67) ~[Vault.jar:?]
	at com.extendedclip.papi.expansion.vault.VaultPermsHook.getPlayerPrefix(VaultPermsHook.java:160) ~[?:?]
	at com.extendedclip.papi.expansion.vault.VaultPermsHook.onPlaceholderRequest(VaultPermsHook.java:112) ~[?:?]
	at com.extendedclip.papi.expansion.vault.VaultExpansion.onRequest(VaultExpansion.java:105) ~[?:?]
	at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:234) ~[PlaceholderAPI-2.10.3%20(1).jar:?]
	at me.clip.placeholderapi.PlaceholderAPI.setPlaceholders(PlaceholderAPI.java:374) ~[PlaceholderAPI-2.10.3%20(1).jar:?]
	at me.clip.deluxechat.DeluxeChat.getFancyChatFormat(DeluxeChat.java:586) ~[DeluxeChat-1.13.1.jar:?]
	at me.clip.deluxechat.DeluxeCommands.onCommand(DeluxeCommands.java:204) ~[DeluxeChat-1.13.1.jar:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[server.jar:git-PaperSpigot-"4c7641d"]
	... 15 more`

**Comment by Sleaker** [comment]
This isn't a Vault issue. this is a problem with one of the plugins on your system trying to make calls into a permission system that doesn't exist. looks like either dchat, or whatever is at com.extendedclip.papi.expansion.vault.VaultPermsHook.
