### ISSUE TITLE
The restrictions on the number of WG privates don't work.

### ISSUE THREAD

**Issue by Awec0m** [MilkBowl/Vault#811]
Hello! There was a problem: when trying to lock the 4th region it does not allow to do this, although in the config set:
`max-region-count-per-player:
default: 3
fly: 4
vip: 5
creative: 6
premium: 8
king: 10
god: 20`
An error appears in the console:
`[14:12:12 WARN]: java.lang.UnsupportedOperationException: SuperPerms no group permissions.
[14:12:12 WARN]: at net.milkbowl.vault.permission.plugins.Permission_SuperPerms.getPlayerGroups(Permission_SuperPerms.java:91)
[14:12:12 WARN]: at net.milkbowl.vault.permission.Permission.getPlayerGroups(Permission.java:637)
[14:12:12 WARN]: at net.milkbowl.vault.permission.Permission.getPlayerGroups(Permission.java:649)
[14:12:12 WARN]: at com.sk89q.wepif.VaultResolver.getGroups(VaultResolver.java:115)
[14:12:12 WARN]: at com.sk89q.wepif.PermissionsResolverManager.getGroups(PermissionsResolverManager.java:180)
[14:12:12 WARN]: at com.sk89q.worldguard.bukkit.WorldGuardPlugin.getGroups(WorldGuardPlugin.java:330)
[14:12:12 WARN]: at com.sk89q.worldguard.bukkit.BukkitPlayer.getGroups(BukkitPlayer.java:207)
[14:12:12 WARN]: at com.sk89q.worldguard.config.WorldConfiguration.getMaxRegionCount(WorldConfiguration.java:247)
[14:12:12 WARN]: at com.sk89q.worldguard.commands.region.RegionCommands.claim(RegionCommands.java:266)
[14:12:12 WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:12:12 WARN]: at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[14:12:12 WARN]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[14:12:12 WARN]: at java.lang.reflect.Method.invoke(Unknown Source)
[14:12:12 WARN]: at com.sk89q.minecraft.util.commands.CommandsManager.invokeMethod(CommandsManager.java:526)
[14:12:12 WARN]: at com.sk89q.minecraft.util.commands.CommandsManager.executeMethod(CommandsManager.java:514)
[14:12:12 WARN]: at com.sk89q.minecraft.util.commands.CommandsManager.executeMethod(CommandsManager.java:469)
[14:12:12 WARN]: at com.sk89q.minecraft.util.commands.CommandsManager.execute(CommandsManager.java:407)
[14:12:12 WARN]: at com.sk89q.worldguard.bukkit.WorldGuardPlugin.onCommand(WorldGuardPlugin.java:273)
[14:12:12 WARN]: at com.sk89q.bukkit.util.DynamicPluginCommand.execute(DynamicPluginCommand.java:54)
[14:12:12 WARN]: at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[14:12:12 WARN]: at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:794)
[14:12:12 WARN]: at net.minecraft.server.v1_16_R1.PlayerConnection.handleCommand(PlayerConnection.java:1908)
[14:12:12 WARN]: at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1719)
[14:12:12 WARN]: at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:47)
[14:12:12 WARN]: at net.minecraft.server.v1_16_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
[14:12:12 WARN]: at net.minecraft.server.v1_16_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23)
[14:12:12 WARN]: at net.minecraft.server.v1_16_R1.TickTask.run(SourceFile:18)
[14:12:12 WARN]: at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[14:12:12 WARN]: at net.minecraft.server.v1_16_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[14:12:12 WARN]: at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[14:12:12 WARN]: at net.minecraft.server.v1_16_R1.MinecraftServer.aZ(MinecraftServer.java:1136)
[14:12:12 WARN]: at net.minecraft.server.v1_16_R1.MinecraftServer.executeNext(MinecraftServer.java:1129)
[14:12:12 WARN]: at net.minecraft.server.v1_16_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[14:12:12 WARN]: at net.minecraft.server.v1_16_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1090)
[14:12:12 WARN]: at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1004)
[14:12:12 WARN]: at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[14:12:12 WARN]: at java.lang.Thread.run(Unknown Source)`

Permissions plugin - LuckPerms, group - fly
Vault installed
Paper 1.16.
How to fix?

**Comment by Sleaker** [comment]
worldguard attempted to use the Vault SuperPerms resolver to find group permissions (which don't exist). when it should be attempting a lookup in LuckPerms. Worldguard perhaps isn't detecting you have luckperms installed, or perhaps there's an incompatibility in here somewhere.  Either way, not a Vault issue.
