### ISSUE TITLE
Vault fails to load

### ISSUE THREAD

**Issue by retep998** [MilkBowl/Vault#816]
Minecraft 1.16.1 using git-Paper-111 using Vault 1.7.3 downloaded from https://dev.bukkit.org/projects/vault/files/3007470
```
Could not load 'plugins\Vault.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:170) ~[patched_1.16.1.jar:git-Paper-111]
at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:148) ~[patched_1.16.1.jar:git-Paper-111]
at org.bukkit.craftbukkit.v1_16_R1.CraftServer.loadPlugins(CraftServer.java:388) ~[patched_1.16.1.jar:git-Paper-111]
at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:208) ~[patched_1.16.1.jar:git-Paper-111]
at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:940) ~[patched_1.16.1.jar:git-Paper-111]
at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-111]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
Caused by: java.util.zip.ZipException: invalid CEN header (bad signature)
at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_251]
at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_251]
at java.util.zip.ZipFile.<init>(Unknown Source) ~[?:1.8.0_251]
at java.util.jar.JarFile.<init>(Unknown Source) ~[?:1.8.0_251]
at java.util.jar.JarFile.<init>(Unknown Source) ~[?:1.8.0_251]
at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:158) ~[patched_1.16.1.jar:git-Paper-111]
... 6 more
```

**Comment by retep998** [comment]
I reuploaded the exact same `Vault.jar` to the server a second time and now it loads just fine. Likely just a corrupted file somehow.
