### ISSUE TITLE
Vault causes server to crash 15 minutes after update check

### ISSUE THREAD

**Issue by Mobmaker55** [MilkBowl/Vault#827]
Multiple times, exactly 15 minutes after vault checks for an update, the server crashes. Kinda sus, might just be me tho :/
```
[16:11:02] [Craft Scheduler Thread - 732/INFO]: [Vault] No new version available
[16:26:40] [Server console handler/ERROR]: Caught previously unhandled exception :
java.io.IOError: java.io.IOException: Input/output error
	at org.jline.keymap.BindingReader.readCharacter(BindingReader.java:143) ~[patched_1.16.3.jar:git-Paper-196]
	at org.jline.keymap.BindingReader.readBinding(BindingReader.java:110) ~[patched_1.16.3.jar:git-Paper-196]
	at org.jline.keymap.BindingReader.readBinding(BindingReader.java:61) ~[patched_1.16.3.jar:git-Paper-196]
	at org.jline.reader.impl.LineReaderImpl.doReadBinding(LineReaderImpl.java:848) ~[patched_1.16.3.jar:git-Paper-196]
	at org.jline.reader.impl.LineReaderImpl.readBinding(LineReaderImpl.java:868) ~[patched_1.16.3.jar:git-Paper-196]
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:575) ~[patched_1.16.3.jar:git-Paper-196]
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:418) ~[patched_1.16.3.jar:git-Paper-196]
	at net.minecrell.terminalconsole.SimpleTerminalConsole.readCommands(SimpleTerminalConsole.java:158) ~[patched_1.16.3.jar:git-Paper-196]
	at net.minecrell.terminalconsole.SimpleTerminalConsole.start(SimpleTerminalConsole.java:141) ~[patched_1.16.3.jar:git-Paper-196]
	at net.minecraft.server.v1_16_R2.DedicatedServer$1.run(DedicatedServer.java:64) ~[patched_1.16.3.jar:git-Paper-196]
Caused by: java.io.IOException: Input/output error
	at java.io.FileInputStream.read0(Native Method) ~[?:1.8.0_265]
	at java.io.FileInputStream.read(FileInputStream.java:207) ~[?:1.8.0_265]
	at org.jline.terminal.impl.AbstractPty$PtyInputStream.read(AbstractPty.java:73) ~[patched_1.16.3.jar:git-Paper-196]
	at org.jline.utils.NonBlockingInputStream.read(NonBlockingInputStream.java:62) ~[patched_1.16.3.jar:git-Paper-196]
	at org.jline.utils.NonBlocking$NonBlockingInputStreamReader.read(NonBlocking.java:168) ~[patched_1.16.3.jar:git-Paper-196]
	at org.jline.utils.NonBlockingReader.read(NonBlockingReader.java:57) ~[patched_1.16.3.jar:git-Paper-196]
	at org.jline.keymap.BindingReader.readCharacter(BindingReader.java:133) ~[patched_1.16.3.jar:git-Paper-196]
	... 9 more
```
and another example: 
```
[23:24:30] [Craft Scheduler Thread - 735/INFO]: [Vault] Checking for Updates ... 
[23:24:31] [Craft Scheduler Thread - 735/INFO]: [Vault] No new version available
[23:40:16] [Server console handler/ERROR]: Caught previously unhandled exception :
java.io.IOError: java.io.IOException: Input/output error
	at org.jline.keymap.BindingReader.readCharacter(BindingReader.java:143) ~[patched_1.16.2.jar:git-Paper-186]
	at org.jline.keymap.BindingReader.readBinding(BindingReader.java:110) ~[patched_1.16.2.jar:git-Paper-186]
	at org.jline.keymap.BindingReader.readBinding(BindingReader.java:61) ~[patched_1.16.2.jar:git-Paper-186]
	at org.jline.reader.impl.LineReaderImpl.doReadBinding(LineReaderImpl.java:848) ~[patched_1.16.2.jar:git-Paper-186]
	at org.jline.reader.impl.LineReaderImpl.readBinding(LineReaderImpl.java:868) ~[patched_1.16.2.jar:git-Paper-186]
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:575) ~[patched_1.16.2.jar:git-Paper-186]
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:418) ~[patched_1.16.2.jar:git-Paper-186]
	at net.minecrell.terminalconsole.SimpleTerminalConsole.readCommands(SimpleTerminalConsole.java:158) ~[patched_1.16.2.jar:git-Paper-186]
	at net.minecrell.terminalconsole.SimpleTerminalConsole.start(SimpleTerminalConsole.java:141) ~[patched_1.16.2.jar:git-Paper-186]
	at net.minecraft.server.v1_16_R2.DedicatedServer$1.run(DedicatedServer.java:66) ~[patched_1.16.2.jar:git-Paper-186]
Caused by: java.io.IOException: Input/output error
	at java.io.FileInputStream.read0(Native Method) ~[?:1.8.0_265]
	at java.io.FileInputStream.read(FileInputStream.java:207) ~[?:1.8.0_265]
	at org.jline.terminal.impl.AbstractPty$PtyInputStream.read(AbstractPty.java:73) ~[patched_1.16.2.jar:git-Paper-186]
	at org.jline.utils.NonBlockingInputStream.read(NonBlockingInputStream.java:62) ~[patched_1.16.2.jar:git-Paper-186]
	at org.jline.utils.NonBlocking$NonBlockingInputStreamReader.read(NonBlocking.java:168) ~[patched_1.16.2.jar:git-Paper-186]
	at org.jline.utils.NonBlockingReader.read(NonBlockingReader.java:57) ~[patched_1.16.2.jar:git-Paper-186]
	at org.jline.keymap.BindingReader.readCharacter(BindingReader.java:133) ~[patched_1.16.2.jar:git-Paper-186]
	... 9 more
```

It really looks like it might be Vault's fault, but then again, I don't know for sure. Help would be appreciated :)

**Comment by Sleaker** [comment]
This has nothing to do with Vault, this is an I/O error when reading from your terminal.
