### ISSUE TITLE
1.16.5 ERROR

### ISSUE THREAD

**Issue by uRyanxD** [MilkBowl/Vault#846]
[17:35:37] [Server thread/ERROR]: Encountered an unexpected exception
java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1493) ~[?:?]
	at java.util.HashMap$ValueIterator.next(HashMap.java:1521) ~[?:?]
	at java.util.Collections$UnmodifiableCollection$1.next(Collections.java:1047) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.help.SimpleHelpMap.initializeCommands(SimpleHelpMap.java:127) ~[patched_1.16.5.jar:git-Paper-469]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:428) ~[patched_1.16.5.jar:git-Paper-469]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:465) ~[patched_1.16.5.jar:git-Paper-469]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239) ~[patched_1.16.5.jar:git-Paper-469]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:936) ~[patched_1.16.5.jar:git-Paper-469]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174) ~[patched_1.16.5.jar:git-Paper-469]
	at java.lang.Thread.run(Thread.java:834) [?:?]
	
	
	Starting and crashing the server

**Comment by Geolykt** [comment]
It doesn't look as if Vault is responsible for this crash due to it's passiveness
