### ISSUE TITLE
Could not load 'plugins/Vault.jar' in folder 'plugins'

### ISSUE THREAD

**Issue by psyu** [MilkBowl/Vault#850]
Running a Paper Minecraft server on 1.16.5 and Vault refuses to work.
I've attached the log, if you need more information let me know.

[latest.log](https://github.com/MilkBowl/Vault/files/6415161/latest.log)

**Comment by Geolykt** [comment]
Did you chmod the jar into the correct mode?

**Comment by psyu** [comment]
Awesome that worked and I feel like a complete muppet. Thanks for the help friend.

**Comment by iRayanKhan** [comment]
I am getting the same error regarding the plugin not loading, but caused by ```json5 zip END```

I tried using Spigot 1.17.1 and 1.17.0.

I am also using Vault 1.7.3

```json5
[22:58:23] [Server thread/ERROR]: Could not load 'plugins/Vault.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:178) ~[spigot.jar:3170-Spigot-a483d2c-ec116f6]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:144) ~[spigot.jar:3170-Spigot-a483d2c-ec116f6]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:384) ~[spigot.jar:3170-Spigot-a483d2c-ec116f6]
	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:232) ~[spigot.jar:3170-Spigot-a483d2c-ec116f6]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:987) ~[spigot.jar:3170-Spigot-a483d2c-ec116f6]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:307) ~[spigot.jar:3170-Spigot-a483d2c-ec116f6]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.util.zip.ZipException: zip END header not found
	at java.util.zip.ZipFile$Source.zerror(ZipFile.java:1587) ~[?:?]
	at java.util.zip.ZipFile$Source.findEND(ZipFile.java:1441) ~[?:?]
	at java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1450) ~[?:?]
	at java.util.zip.ZipFile$Source.<init>(ZipFile.java:1263) ~[?:?]
	at java.util.zip.ZipFile$Source.get(ZipFile.java:1225) ~[?:?]
	at java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:706) ~[?:?]
	at java.util.zip.ZipFile.<init>(ZipFile.java:240) ~[?:?]
	at java.util.zip.ZipFile.<init>(ZipFile.java:171) ~[?:?]
	at java.util.jar.JarFile.<init>(JarFile.java:348) ~[?:?]
	at java.util.jar.JarFile.<init>(JarFile.java:319) ~[?:?]
	at java.util.jar.JarFile.<init>(JarFile.java:285) ~[?:?]
	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:166) ~[spigot.jar:3170-Spigot-a483d2c-ec116f6]
	... 6 more
```

**Comment by Geolykt** [comment]
This is either a case of a corrupted plugin jar (try reinstalling vault) or a known spigot bug (though I do not know what causes this).
I have heard it is caused by disabling the plugin but this makes little sense as why would you disable vault?
