### ISSUE TITLE
Update for Version 1.17

### ISSUE THREAD

**Issue by Pretoreaner** [MilkBowl/Vault#853]
Hi there,
is there an update for mincraft 1.17 comming or is the project depricated?
Greets
Preto

**Comment by Geolykt** [comment]
Short answer: it is already out

Long answer: Vault is pretty much version-agnostic. To get it to break with a minecraft update is a feat in itself.

**Comment by Pretoreaner** [comment]
ATM i get the following error:

[22:21:53 WARN]: java.lang.NullPointerException: Cannot invoke "net.milkbowl.vault.economy.Economy.getBalance(org.bukkit.OfflinePlayer)" because "this.econ" is null
[22:21:53 WARN]:        at com.plotsquared.bukkit.util.BukkitEconHandler.getBalance(BukkitEconHandler.java:110)
[22:21:53 WARN]:        at com.plotsquared.core.util.EconHandler.getMoney(EconHandler.java:58)
[22:21:53 WARN]:        at com.plotsquared.bukkit.util.BukkitEconHandler.getMoney(BukkitEconHandler.java:71)
[22:21:53 WARN]:        at com.plotsquared.core.command.Merge.onCommand(Merge.java:197)
[22:21:53 WARN]:        at com.plotsquared.core.command.SubCommand.execute(SubCommand.java:57)

**Comment by Geolykt** [comment]
Always get your economy lazily smh

**Comment by Pretoreaner** [comment]
eco is EssentialsX for Version 1.17. it seams to run normal because when i deactivate vault the error is gone

**Comment by itdevsteve** [comment]
> 
> 
> Short answer: it is already out
> 
> Long answer: Vault is pretty much version-agnostic. To get it to break with a minecraft update is a feat in itself.

The servers now require a major java runtime shift to 16, from 8.  I think the original poster is checking for verification that there are no problems running it under the new runtime engine.   Some plugins are having that issue.

**Comment by Geolykt** [comment]
> > Short answer: it is already out
> > Long answer: Vault is pretty much version-agnostic. To get it to break with a minecraft update is a feat in itself.
> 
> The servers now require a major java runtime shift to 16, from 8. I think the original poster is checking for verification that there are no problems running it under the new runtime engine. Some plugins are having that issue.

I do not get that sentiment. Even then, Vault is not using any reflection hackery so it is safe to use

**Comment by Sleaker** [comment]
@itdevsteve as has been mentioned, the bytecode compatibility being at 8 should not matter.
