### ISSUE TITLE
Could not submit plugin stats of Vault

### ISSUE THREAD

**Issue by hoehoetvhss** [MilkBowl/Vault#869]
`
[12:58:34 WARN]: [Vault] Could not submit plugin stats of Vault
java.io.IOException: Server returned HTTP response code: 429 for URL: https://bStats.org/submitData/bukkit
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1997) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589) ~[?:?]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224) ~[?:?]
        at net.milkbowl.vault.metrics.bukkit.Metrics.sendData(Metrics.java:353) ~[Vault.jar:?]
        at net.milkbowl.vault.metrics.bukkit.Metrics.lambda$submitData$0(Metrics.java:305) ~[Vault.jar:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
`

**Comment by Geolykt** [comment]
For reference HTTP response code 429 is "Too Many Requests". If it happens once (especially after server restarts) it isn't much of an issue, but if it happens more often it might be something to look into

**Comment by hoehoetvhss** [comment]
It only occurs after rebooting the server and does not occur after that, so it would be better to assume that there is no problem. Thank you.
