### ISSUE TITLE
HOST ERROR? 

### ISSUE THREAD

**Issue by Klover91** [MilkBowl/Vault#904]
hi, what should i do with this error?
i have the server on a monthly billed host

`[28.09 23:04:22] [Server] [INFO] [Vault] Enabling Vault v1.7.3-b131
[28.09 23:04:22] [Server] [WARN] java.net.NoRouteToHostException: No route to host
[28.09 23:04:22] [Server] [WARN] 	at java.base/sun.nio.ch.Net.connect0(Native Method)
[28.09 23:04:22] [Server] [WARN] 	at java.base/sun.nio.ch.Net.connect(Net.java:579)
[28.09 23:04:22] [Server] [WARN] 	at java.base/sun.nio.ch.Net.connect(Net.java:568)
[28.09 23:04:22] [Server] [WARN] 	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
[28.09 23:04:22] [Server] [WARN] 	at java.base/java.net.Socket.connect(Socket.java:633)
[28.09 23:04:22] [Server] [WARN] 	at java.base/java.net.Socket.connect(Socket.java:583)
[28.09 23:04:22] [Server] [WARN] 	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:183)
[28.09 23:04:22] [Server] [WARN] 	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:498)
[28.09 23:04:22] [Server] [WARN] 	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:603)
[28.09 23:04:22] [Server] [WARN] 	at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:246)
[28.09 23:04:22] [Server] [WARN] 	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:351)
[28.09 23:04:22] [Server] [WARN] 	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:373)
[28.09 23:04:22] [Server] [WARN] 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1309)
[28.09 23:04:22] [Server] [WARN] 	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242)
[28.09 23:04:22] [Server] [WARN] 	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)
[28.09 23:04:22] [Server] [WARN] 	at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1057)
[28.09 23:04:22] [Server] [WARN] 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665)
[28.09 23:04:22] [Server] [WARN] 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
[28.09 23:04:22] [Server] [WARN] 	at Vault.jar//Updater.a(:95)
[28.09 23:04:22] [Server] [WARN] 	at Vault.jar//Updater.init(:37)
[28.09 23:04:22] [Server] [WARN] 	at Vault.jar//net.milkbowl.vault.Vault.onEnable(Vault.java)
[28.09 23:04:22] [Server] [WARN] 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[28.09 23:04:22] [Server] [WARN] 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[28.09 23:04:22] [Server] [WARN] 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542)
[28.09 23:04:22] [Server] [WARN] 	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565)
[28.09 23:04:22] [Server] [WARN] 	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479)
[28.09 23:04:22] [Server] [WARN] 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:279)
[28.09 23:04:22] [Server] [WARN] 	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1100)
[28.09 23:04:22] [Server] [WARN] 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
[28.09 23:04:22] [Server] [WARN] 	at java.base/java.lang.Thread.run(Thread.java:833)
[28.09 23:04:22] [Server] [ERROR] Error occurred while enabling Vault v1.7.3-b131 (Is it up to date?)
[28.09 23:04:22] [Server] java.lang.Errorjava.net.NoRouteToHostException: No route to host
[28.09 23:04:22] [Server] 	at Updater.init(:51) ~[Vault.jar:?]
[28.09 23:04:22] [Server] 	at net.milkbowl.vault.Vault.onEnable(Vault.java) ~[Vault.jar:?]
[28.09 23:04:22] [Server] 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
[28.09 23:04:22] [Server] 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
[28.09 23:04:22] [Server] 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
[28.09 23:04:22] [Server] 	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565) ~[paper-1.19.2.jar:git-Paper-177]
[28.09 23:04:22] [Server] 	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479) ~[paper-1.19.2.jar:git-Paper-177]
[28.09 23:04:22] [Server] 	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:279) ~[paper-1.19.2.jar:git-Paper-177]
[28.09 23:04:22] [Server] 	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.19.2.jar:git-Paper-177]
[28.09 23:04:22] [Server] 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-177]
[28.09 23:04:22] [Server] 	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[28.09 23:04:22] [Server] Caused byjava.net.NoRouteToHostException: No route to host
[28.09 23:04:22] [Server] 	at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
[28.09 23:04:22] [Server] 	at sun.nio.ch.Net.connect(Net.java:579) ~[?:?]
[28.09 23:04:22] [Server] 	at sun.nio.ch.Net.connect(Net.java:568) ~[?:?]
[28.09 23:04:22] [Server] 	at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588) ~[?:?]
[28.09 23:04:22] [Server] 	at java.net.Socket.connect(Socket.java:633) ~[?:?]
[28.09 23:04:22] [Server] 	at java.net.Socket.connect(Socket.java:583) ~[?:?]
[28.09 23:04:22] [Server] 	at sun.net.NetworkClient.doConnect(NetworkClient.java:183) ~[?:?]
[28.09 23:04:22] [Server] 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:498) ~[?:?]
[28.09 23:04:22] [Server] 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:603) ~[?:?]
[28.09 23:04:22] [Server] 	at sun.net.www.http.HttpClient.<init>(HttpClient.java:246) ~[?:?]
[28.09 23:04:22] [Server] 	at sun.net.www.http.HttpClient.New(HttpClient.java:351) ~[?:?]
[28.09 23:04:22] [Server] 	at sun.net.www.http.HttpClient.New(HttpClient.java:373) ~[?:?]
[28.09 23:04:22] [Server] 	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1309) ~[?:?]
[28.09 23:04:22] [Server] 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242) ~[?:?]
[28.09 23:04:22] [Server] 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128) ~[?:?]
[28.09 23:04:22] [Server] 	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1057) ~[?:?]
[28.09 23:04:22] [Server] 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665) ~[?:?]
[28.09 23:04:22] [Server] 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589) ~[?:?]
[28.09 23:04:22] [Server] 	at Updater.a(:95) ~[Vault.jar:?]
[28.09 23:04:22] [Server] 	at Updater.init(:37) ~[Vault.jar:?]
[28.09 23:04:22] [Server] 	... more
[28.09 23:04:22] [Server] [INFO] [Vault] Disabling Vault v1.7.3-b131`

**Comment by Sleaker** [comment]
Looks like the vault update checker can't connect. this is fine it is not a required piece.

**Comment by Jack1424** [comment]
> Looks like the vault update checker can't connect. this is fine it is not a required piece.

It looks like Vault is disabling at the end though

**Comment by cerealcable** [comment]
The words "Disabling Vault" do not appear in our source code. The log presented isn't well formatted and it appears there is missing info as well, not sure what " ... more " indicates is missing. As mentioned, this error would not be a problem for Vault's operations.

**Comment by Jack1424** [comment]
I believe that the "enabling" and "disabling" messages are part of the Bukkit/Spigot source code and are displayed whenever the server enables or disables a plugin.

I think that, since this exception occurs in Vault's onEnable method, the server is treating this as a fatal error and disabling the plugin.

**Comment by cerealcable** [comment]
Does setting the update-check config value to false resolve the problem for you? I would have expected to see a log line containing "Checking for Updates ... " which we don't see in your file above. However it's very difficult to read because none of the line breaks are shown.

**Comment by Geolykt** [comment]
Properly formatted logs for reference (how hard is it to use tripple backticks?):
```
[28.09 23:04:22] [Server] [INFO] [Vault] Enabling Vault v1.7.3-b131
[28.09 23:04:22] [Server] [WARN] java.net.NoRouteToHostException: No route to host
[28.09 23:04:22] [Server] [WARN] at java.base/sun.nio.ch.Net.connect0(Native Method)
[28.09 23:04:22] [Server] [WARN] at java.base/sun.nio.ch.Net.connect(Net.java:579)
[28.09 23:04:22] [Server] [WARN] at java.base/sun.nio.ch.Net.connect(Net.java:568)
[28.09 23:04:22] [Server] [WARN] at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
[28.09 23:04:22] [Server] [WARN] at java.base/java.net.Socket.connect(Socket.java:633)
[28.09 23:04:22] [Server] [WARN] at java.base/java.net.Socket.connect(Socket.java:583)
[28.09 23:04:22] [Server] [WARN] at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:183)
[28.09 23:04:22] [Server] [WARN] at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:498)
[28.09 23:04:22] [Server] [WARN] at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:603) 
[28.09 23:04:22] [Server] [WARN] at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:246)
[28.09 23:04:22] [Server] [WARN] at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:351)
[28.09 23:04:22] [Server] [WARN] at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:373)
[28.09 23:04:22] [Server] [WARN] at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1309)
[28.09 23:04:22] [Server] [WARN] at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242)
[28.09 23:04:22] [Server] [WARN] at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128)
[28.09 23:04:22] [Server] [WARN] at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1057)
[28.09 23:04:22] [Server] [WARN] at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665)
[28.09 23:04:22] [Server] [WARN] at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589)
[28.09 23:04:22] [Server] [WARN] at Vault.jar//Updater.a(:95)
[28.09 23:04:22] [Server] [WARN] at Vault.jar//Updater.init(:37)
[28.09 23:04:22] [Server] [WARN] at Vault.jar//net.milkbowl.vault.Vault.onEnable(Vault.java)
[28.09 23:04:22] [Server] [WARN] at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[28.09 23:04:22] [Server] [WARN] at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[28.09 23:04:22] [Server] [WARN] at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542)
[28.09 23:04:22] [Server] [WARN] at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565)
[28.09 23:04:22] [Server] [WARN] at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479)
[28.09 23:04:22] [Server] [WARN] at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:279)
[28.09 23:04:22] [Server] [WARN] at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1100)
[28.09 23:04:22] [Server] [WARN] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
[28.09 23:04:22] [Server] [WARN] at java.base/java.lang.Thread.run(Thread.java:833)
[28.09 23:04:22] [Server] [ERROR] Error occurred while enabling Vault v1.7.3-b131 (Is it up to date?)
[28.09 23:04:22] [Server] java.lang.Errorjava.net.NoRouteToHostException: No route to host
[28.09 23:04:22] [Server] at Updater.init(:51) ~[Vault.jar:?]
[28.09 23:04:22] [Server] at net.milkbowl.vault.Vault.onEnable(Vault.java) ~[Vault.jar:?]
[28.09 23:04:22] [Server] at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
[28.09 23:04:22] [Server] at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
[28.09 23:04:22] [Server] at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542) ~[paper-api-1.19.2-R0.1-SNAPSHOT.jar:?]
[28.09 23:04:22] [Server] at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:565) ~[paper-1.19.2.jar:git-Paper-177]
[28.09 23:04:22] [Server] at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:479) ~[paper-1.19.2.jar:git-Paper-177]
[28.09 23:04:22] [Server] at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:279) ~[paper-1.19.2.jar:git-Paper-177]
[28.09 23:04:22] [Server] at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.19.2.jar:git-Paper-177]
[28.09 23:04:22] [Server] at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.2.jar:git-Paper-177]
[28.09 23:04:22] [Server] at java.lang.Thread.run(Thread.java:833) ~[?:?]
[28.09 23:04:22] [Server] Caused by java.net.NoRouteToHostException: No route to host
[28.09 23:04:22] [Server] at sun.nio.ch.Net.connect0(Native Method) ~[?:?]
[28.09 23:04:22] [Server] at sun.nio.ch.Net.connect(Net.java:579) ~[?:?]
[28.09 23:04:22] [Server] at sun.nio.ch.Net.connect(Net.java:568) ~[?:?]
[28.09 23:04:22] [Server] at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588) ~[?:?]
[28.09 23:04:22] [Server] at java.net.Socket.connect(Socket.java:633) ~[?:?]
[28.09 23:04:22] [Server] at java.net.Socket.connect(Socket.java:583) ~[?:?]
[28.09 23:04:22] [Server] at sun.net.NetworkClient.doConnect(NetworkClient.java:183) ~[?:?]
[28.09 23:04:22] [Server] at sun.net.www.http.HttpClient.openServer(HttpClient.java:498) ~[?:?]
[28.09 23:04:22] [Server] at sun.net.www.http.HttpClient.openServer(HttpClient.java:603) ~[?:?]
[28.09 23:04:22] [Server] at sun.net.www.http.HttpClient.<init>(HttpClient.java:246) ~[?:?]
[28.09 23:04:22] [Server] at sun.net.www.http.HttpClient.New(HttpClient.java:351) ~[?:?]
[28.09 23:04:22] [Server] at sun.net.www.http.HttpClient.New(HttpClient.java:373) ~[?:?]
[28.09 23:04:22] [Server] at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1309) ~[?:?]
[28.09 23:04:22] [Server] at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242) ~[?:?]
[28.09 23:04:22] [Server] at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128) ~[?:?]
[28.09 23:04:22] [Server] at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1057) ~[?:?]
[28.09 23:04:22] [Server] at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665) ~[?:?]
[28.09 23:04:22] [Server] at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589) ~[?:?]
[28.09 23:04:22] [Server] at Updater.a(:95) ~[Vault.jar:?]
[28.09 23:04:22] [Server] at Updater.init(:37) ~[Vault.jar:?]
[28.09 23:04:22] [Server] ... more
[28.09 23:04:22] [Server] [INFO] [Vault] Disabling Vault v1.7.3-b131
```

**Comment by Geolykt** [comment]
I am quite certain the the `Updater.a` method is not part of standard Vault and as such may have been malicious (it certainly wasn't compiled by standard javac since the source file is blanked out). Can anyone comment on that?

**Comment by cerealcable** [comment]
The updater block within Vault is here: https://github.com/MilkBowl/Vault/blob/master/src/net/milkbowl/vault/Vault.java#L136-L153

It is an async task so perhaps this is why we see Updater.a, but I'm a little surprised to see the class Updater being used regardless since I don't see anywhere in that code where we would give it such a strong class name as "Updater". Perhaps it's been too long since I've been deep enough into Java though.

Something smells wrong still. I still expected to see some of the log statements from that branch of code I linked specifically which are not present within this log.

**Comment by Jack1424** [comment]
@Klover91 do you think that you could upload the Vault.jar file that you're using or let us know where you got it?

**Comment by Sleaker** [comment]
It appears your host blocks connections to curseforge API. You'll want to get them to fix this if you want to be notified of new versions, but this wont affect the functionality. You can also turn off the update checker using the config.yaml with `update-check: false` 

EDIT: thanks to @Geolykt - for digging more into this, looks like it's malware injection. unfortunately, and not related to Vault specifically. Suggest wiping your plugins and re-installing. Also.. maybe need to do more than just that, not sure what this malware does.

**Comment by Geolykt** [comment]
After thinking more thoroughly this issue is not caused by the host blocking connections to curseforge APIs but rather by the infamous Updater.class (https://www.spigotmc.org/threads/1-19-1-fatal-error-converting-plugin-updater-class.567801/) malware.
Disabling update checking does not do anything as the malware isn't part of vault.
